apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemma-inference
spec:
  template:
    spec:
      containers:
        - name: gemma
          resources:
            requests:
              cpu: "16"
              memory: 64Gi
            limits:
              cpu: "24"
              memory: 96Gi
